logging:
  level: INFO
  loggers:
    com.github.trastle: INFO

server:
  applicationConnectors:
    - type: http
      port: 22200
  adminConnectors:
    - type: http
      port: 22201

haverland:
  username: ${HAVERLAND_USERNAME:-}
  password: ${HAVERLAND_PASSWORD:-}
