version: '3'
services:

  haverland-prometheus-exporter:
    image: trastle/haverland-smartwave-prometheus-exporter
    build: .
    ports:
      - 22200:22200
    environment:
      - HAVERLAND_USERNAME=your_username
      - HAVERLAND_PASSWORD=your_password
