version: '3'
services:

  heatertool:
    image: trastle/haverland-smartwave-prometheus-exporter
    build: .
    ports:
      - 22200:22200
    environment:
      - HAVERLAND_USERNAME=username
      - HAVERLAND_PASSWORD=password
